HomeShopAdmin/Models/ShippingType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ShippingType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShippingType()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public int ShippingID { get; set; }
        public string ShippingName { get; set; }

        [DisplayFormat(DataFormatString = "{0:C2}")]
        public Nullable<decimal> ShippingCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}

HomeShopAdmin/Controllers/ShippingController.cs
using System.Web.Mvc;
using BeyondThemes.BeyondAdmin.Models;
using System.Linq;
using System.Net;
using System.Data.Entity;

namespace BeyondThemes.BeyondAdmin.Controllers
{
    [Authorize]
    public class ShippingController : Controller
    {

        HomeStoreEntities db = new HomeStoreEntities();
        
        public ActionResult Index()
        {           
            return View(db.ShippingTypes.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShippingName,ShippingCost")] ShippingType shipType)
        {
            if (ModelState.IsValid)
            {
                db.ShippingTypes.Add(shipType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(shipType);
        }

        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ShippingType shipType = db.ShippingTypes.Find(id);

            if(shipType == null)
            {
                return HttpNotFound();
            }

            return View(shipType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShippingID,ShippingName,ShippingCost")]ShippingType shipType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shipType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(shipType);
        }

        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ShippingType shipType = db.ShippingTypes.Find(id);

            if(shipType == null)
            {
                return HttpNotFound();
            }

            return View(shipType);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ShippingType shipType = db.ShippingTypes.Find(id);
            db.ShippingTypes.Remove(shipType);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeShopAdmin/Views/Shipping/Create.cshtml
@model BeyondThemes.BeyondAdmin.Models.ShippingType

@{
    ViewBag.Title = "Create New Shipping Type";
    ViewBag.Description = "Shipping List";
    Layout = "~/Views/Shared/_Default.cshtml";
}

<h2>Create New Shipping Type</h2>

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Shipping Type Name</label>
            <div class="col-md-5">
                @Html.EditorFor(m => m.ShippingName, new { htmlAttributes = new {@class = "form-control" }})
                @Html.ValidationMessageFor(m=>m.ShippingName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Shipping Cost</label>
            <div class="col-md-5">
                @Html.EditorFor(m => m.ShippingCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.ShippingCost, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

HomeShopAdmin/Views/Shipping/Delete.cshtml
@model BeyondThemes.BeyondAdmin.Models.ShippingType

@{
    ViewBag.Title = "Delete Shipping Type";
    ViewBag.Description = "Shipping List";
    Layout = "~/Views/Shared/_Default.cshtml";
}

<h3>Are you sure you want to delete @Model.ShippingName?</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions">
        <input type="submit" value="Delete" class="btn btn-danger"  /> | 
        @Html.ActionLink("No","Index","Shipping", null, new { @class = "btn btn-primary" })
    </div>
}

HomeShopAdmin/Views/Shipping/Edit.cshtml
@model BeyondThemes.BeyondAdmin.Models.ShippingType

@{
    ViewBag.Title = "Edit Shipping Type";
    ViewBag.Description = "Shipping List";
    Layout = "~/Views/Shared/_Default.cshtml";
}

<h3>Edit Shipping Type</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger"})
        @Html.HiddenFor(m => m.ShippingID)

        <div class="form-group">
            <label class="control-label col-md-2">Name</label>
            <div class="col-md-5">
                @Html.EditorFor(m => m.ShippingName, new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(m => m.ShippingName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Cost</label>
            <div class="col-md-5">
                @Html.EditorFor(m => m.ShippingCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.ShippingCost, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

HomeShopAdmin/Views/Shipping/Index.cshtml
@model IEnumerable<BeyondThemes.BeyondAdmin.Models.ShippingType>
@{
    ViewBag.Title = "Shipping";
    ViewBag.Description = "Shipping List";
    Layout = "~/Views/Shared/_Default.cshtml";
}

<table class="table">

    <tr>
        <th>Type</th>
        <th>Cost</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@Html.DisplayFor(m => item.ShippingName)</th>
            <th>@Html.DisplayFor(m=> item.ShippingCost)</th>
            <th>@Html.ActionLink("Edit","Edit",new { id=item.ShippingID}) | @Html.ActionLink("Decomission", "Delete", new { id = item.ShippingID })</th>
        </tr>
    }

</table>

<br />

@Html.ActionLink("Create New", "Create", "Shipping", null, new { @class = "btn btn-primary" })